### ISSUE TITLE
Work to be done

### ISSUE THREAD

**Issue by udenizdemirbilek** [ReCoded-Org/capstone-turkey-giftify#31]
- Product Requests Page (where the donator can see the messages from other users asking for the item)
- Requests Page
- Request Component (can render a modal to let the user enter text asking for the item)
- Change Readme.md, edit index.html and remove tags, unnecessary icons
- Multi-language support

**Comment by ceyhungulbas** [comment]
If everyone okay with that I really want to have experience and learn auth, logIn part, so I can take it.

**Comment by ceyhungulbas** [comment]
- Language functionality
